### ISSUE TITLE
Compare model results in March with actual case numbers

### ISSUE THREAD

**Issue by wfmackey** [grattan/covid19.model.sa2#51]
This will be shown at the end of Chapter 3.

**Comment by HughParsonage** [comment]
> Emphasis on the word 'technically'
> 
> ```r
> library(magrittr)
> library(hutils)
> library(data.table)
> stopifnot(isNamespaceLoaded("covid19.model.sa2"))  # don't nest loading
> #> Error: isNamespaceLoaded("covid19.model.sa2") is not TRUE
> covid19.model.sa2::attachme()
> #> The following object is masked from package:hutils:
> #> 
> #>     samp
> myaus <- covid19.model.sa2:::read_typical()
> 
> cases_by_state <- read_sys("time_series_cases.fst")
> deaths_by_state <- read_sys("time_series_deaths.fst")
> recovered_by_state <- read_sys("time_series_recovered.fst")
> 
> # modify recovered by state, e.g.
> states_in_file <- intersect(names(recovered_by_state), states())
> approx_column <- function(x, n = length(x)) {
>   force(n)
>   as.integer(approx(seq_along(x), x, n = n)[["y"]])
> }
> 
> # This won't work -- results in more 'recovered cases' than cases
> # recovered_by_state[1, (states_in_file) := lapply(.SD, coalesce, 0L), .SDcols = c(states_in_file)]
> # recovered_by_state[, (states_in_file) := lapply(.SD, approx_column), .SDcols = c(states_in_file)]
> # recovered_by_state[1, (states_in_file) := lapply(.SD, coalesce, 0L), .SDcols = c(states_in_file)]
> recovered_by_state[, (states_in_file) := lapply(.SD, coalesce, 0L), .SDcols = c(states_in_file)]
> 
> 
> myaus[, Status := set_initial_by_state(state, 
>                                        cases_by_state = cases_by_state,
>                                        deaths_by_state = deaths_by_state,
>                                        recovered_by_state = recovered_by_state,
>                                        first_yday = "2020-03-05",
>                                        .population = .N)]
> myaus[Status != 0L, InfectedOn := yday("2020-03-05") - 11L]
> 
> nPlacesByDestType <-
>   lapply(1:106, function(i) {
>     if (i == 98L) {
>       read_sys("nSupermarkets_by_sa2.fst",
>                columns = "nSupermarkets")[[1L]]
>     } else {
>       integer(0)
>     }
>   })
> 
> aus <- copy(myaus)  # not necessary just in case you need original
> 
> out <- 
>   do_au_simulate(Status = dollars(aus, Status),
>                  InfectedOn = dollars(aus, InfectedOn),
>                  SA2 = dollars(aus, sa2),
>                  hid = dollars(aus, hid),
>                  Age = dollars(aus, Age),
>                  School = dollars(aus, short_school_id),
>                  DZN = dollars(aus, short_dzn),
>                  wid = dollars(aus, wid),
>                  nColleagues = dollars(aus, nColleagues),
>                  PlaceTypeBySA2 = integer(0),
>                  LabourForceStatus = dollars(aus, LabourForceStatus),
>                  SeedOriginal = 1:2048,
>                  Policy = set_policypars(),
>                  MultiPolicy = NULL,
>                  nPlacesByDestType = nPlacesByDestType,
>                  Epi = set_epipars(),
>                  Incubation = rep(14L, nrow(aus)),
>                  Illness = rep(1L, nrow(aus)),
>                  nSupermarketsAvbl = integer(nrow(aus)),
>                  SupermarketTypical = integer(nrow(aus)),
>                  minPlaceID_nPlacesByDestType = minPlaceID_nPlacesByDestType,
>                  yday_start = yday("2020-03-05"),   # as required
>                  days_to_sim = 5,
>                  N = nrow(aus),
>                  display_progress = getOption("covid19.showProgress", 0L),
>                  optionz = getOption("optionz", 0L),
>                  nThread = getOption("covid19.model.sa2_nThread", 1L), 
>                  returner = 2L)
> invisible(out)  # All outputs are large
> ```
> 
> Created on 2020-05-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)

@wfmackey
