### ISSUE TITLE
Lower resistance threshold for children

### ISSUE THREAD

**Issue by wfmackey** [grattan/covid19.model.sa2#61]
To acknowledge lower risk of infection for children, correlate an individual's `resistance` with their age. Use household cluster analysis:

https://journals.lww.com/pidj/Abstract/9000/The_Role_of_Children_in_the_Dynamics_of_Intra.96128.aspx

> 1. In 21 out of 36 adults (>18 years) (58.3%).
> 2. In 13 of 40 children, 5–17 years (32.5%), (P = 0.037 for the difference between group 1 and group 2, risk ratio: 0.61, 95% confidence interval [CI]: 0.39–0.96).
> 3. In 2 of 18 children, 0–4 (<5) years of age (11.8%), (P < 0.002 for the difference between group 1 and group 3, risk ratio: 0.47, 95% CI: 0.30–0.71).

**Comment by HughParsonage** [comment]
Hmm I was actually just looking at age-based infection ratios. Those CI's don't look convincing though.

**Comment by wfmackey** [comment]
I think using something like a `1:0.5:0.2` resistance ratios for adults, 5-17 year olds and < 5 year olds would be better than our current `1:1:1`?

**Comment by wfmackey** [comment]
I think using something like a `1:0.5:0.2` resistance ratios for adults, 5-17 year olds and < 5 year olds would be better than our current `1:1:1`?

**Comment by HughParsonage** [comment]
Is it 5-17 year olds are 61% "less" likely (abstract) or 61% "as" likely (your excerpt)?

**Comment by wfmackey** [comment]
Noting that there is no statistical difference between young and older children, we can say that children (17 and younger) have about half the risk of infection as adults.

**Comment by wfmackey** [comment]
@HughParsonage was this implemented -- if so, what are the rates?
